trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

jobs:
- job: SingleJob
  displayName: 'Build and Deploy'
  variables:
    NODE_VERSION: '20'
  steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
      displayName: 'Use Node.js $(NODE_VERSION)'
    - script: |
        npm ci
      displayName: 'Install dependencies'
    - script: |
        npm run build
      displayName: 'Build Vite app'
    - task: AzureStaticWebApp@0
      displayName: 'Deploy to Azure Static Web App'
      inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
        app_location: '/'
        output_location: 'dist'